import React, { useState } from 'react'
import { Grid, TextField, Button } from '@material-ui/core'
import axios from 'axios'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import baseAddress from '../utils/baseAddress'

async function handleSubmit(title: string, message: string) {
    const payload = JSON.stringify({
        title: title,
        message: message,
    })
    console.log(title)
    try {
        const { data } = await axios.post(`${baseAddress}/api/questions`, payload, {
            headers: { 'Content-Type': 'application/json' },
        })
        console.log(message)
    } catch ({ err }) {
        console.log(err)
    }
}

const Form: React.FC = () => {
    const [title, setTitle] = useState('')
    const [message, setMessage] = useState('')

    return (
        <div>
            <Head>
                <title>Playground | Contribute</title>
                <link rel="manifest" href="/manifest.json" />
                <link rel="apple-touch-icon" href="/playground-logo.png"></link>
                <meta name="theme-color" content="#fff" />
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/playground-logo.png" />
            </Head>
            <Grid container style={{ minHeight: '100vh' }}>
                <Grid item xs={12} sm={6}>
                    <img
                        src="https://cdn.dribbble.com/users/345970/screenshots/14741336/media/0d7f0ffe406091da256fa30df972e439.png"
                        style={{ width: '100%', height: '100%', objectFit: 'cover' }}
                    />
                </Grid>
                <Grid container item xs={12} sm={6} alignItems="center" direction="column" style={{ padding: 10 }}>
                    <div className={styles.form}>
                        <div
                            style={{
                                display: 'flex',
                                flexDirection: 'column',
                            }}
                        >
                            <Grid container justify="center">
                                <img
                                    src="https://res.cloudinary.com/dqlh4eyt8/image/upload/v1630815038/playground-logo_1_jrjppd.png"
                                    className={styles.formLogo}
                                    alt="Playground"
                                />
                            </Grid>

                            <TextField
                                label="Question"
                                margin="normal"
                                type="string"
                                onChange={e => setTitle(e.target.value)}
                                className={styles.formText}
                            />
                            <TextField
                                label="Problem Statement"
                                margin="normal"
                                type="string"
                                onChange={e => setMessage(e.target.value)}
                                className={styles.formText}
                            />
                            <br />
                            <Button color="primary" variant="contained" onClick={() => handleSubmit(title, message)}>
                                Submit
                            </Button>
                        </div>
                    </div>
                </Grid>
            </Grid>
        </div>
    )
}

export default Form
